version: '3.8'

services:
  app:
    build: .
    container_name: todo_app
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      APP_VERSION: "1.0.0"
      DB_HOST: db  
      DB_PORT: 5432
      DB_NAME: todo
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: todo_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
